### ISSUE TITLE
Not detecting when roblox opens

### ISSUE THREAD

**Issue by jwuhlie** [Stefanuk12/R-UWP#3]
title says everything

**Comment by jwuhlie** [comment]
(title changed because I just realized the note left by the maker)

**Comment by Stefanuk12** [comment]
Can you expand a little on this: how do you know that Roblox isn't being detected?

If you can show some screenshots of the console, that would be great too.

**Comment by jwuhlie** [comment]
What i meant by "not detects roblox opening" is that it doesnt output "roblox is open" on the console but does when its closed. The first time I used it im pretty sure it said that roblox was open. Not able to provide any screenshots now but I will def will when i can

**Comment by Stefanuk12** [comment]
With the latest update, this issue has become obsolete as I no longer check if Roblox has opened or not.
